"""
Compass — Skills Registry & Tool Definitions.

Central registry for all skills supported by Compass. Provides a standardized
pattern for registering tools for the router and dispatching execution in orchestrator.
"""

from backend.skills.schemas import (
    ADD_TASK_TOOL,
    QUERY_TASKS_TOOL,
    QUERY_CODE_CONTEXT_TOOL,
    SUMMARIZE_DAY_TOOL,
    QUERY_COURSEWORK_TASKS_TOOL,
    GET_HACKATHON_DEADLINES_TOOL,
    LOG_CODE_SNIPPET_TOOL,
    LOG_CODE_CONTEXT_TOOL,
    SEARCH_WEB_TOOL,
    INGEST_URL_TOOL,
    VERIFY_DEADLINE_TOOL,
    UPDATE_TASK_STATUS_TOOL,
    EDIT_TASK_TOOL,
    DELETE_TASK_TOOL,
    LIST_PROJECTS_TOOL,
    QUERY_COURSEWORK_NOTES_TOOL,
    SUMMARIZE_ACROSS_DOMAINS_TOOL,
    CHAT_TOOL,
    DETECT_DEADLINE_CONFLICTS_TOOL,
    GET_CALENDAR_AVAILABILITY_TOOL,
    PROPOSE_SCHEDULE_TOOL,
    COMMIT_SCHEDULE_TOOL,
    DETECT_SCHEDULE_CONFLICTS_TOOL,
    DELEGATE_TO_SPECIALIST_TOOL,
    ASSESS_FEASIBILITY_TOOL,
    APPLY_TRIAGE_PLAN_TOOL,
    BASE_TOOL_DEFINITIONS,
    get_tool_definitions,
    TOOL_DEFINITIONS,
    MUTATING_TOOLS,
)

from backend.skills.registry import (
    SkillHandler,
    SKILL_REGISTRY,
    register_skill,
    dispatch_skill,
)

# Import all handlers so they register themselves into SKILL_REGISTRY
from backend.skills.handlers import (
    handle_search_web,
    handle_ingest_url,
    handle_verify_deadline,
    handle_query_tasks,
    handle_query_coursework_tasks,
    handle_get_hackathon_deadlines,
    handle_add_task,
    handle_update_task_status,
    handle_edit_task,
    handle_delete_task,
    handle_list_projects,
    handle_detect_deadline_conflicts,
    handle_query_code_context,
    handle_log_code_context,
    handle_log_code_snippet,
    handle_summarize_day,
    handle_query_coursework_notes,
    handle_summarize_across_domains,
    handle_chat_skill,
    handle_get_calendar_availability,
    handle_propose_schedule,
    handle_commit_schedule,
    handle_detect_schedule_conflicts,
    handle_assess_feasibility,
    handle_apply_triage_plan,
    handle_delegate_to_specialist,
)

__all__ = [
    # Schemas & Definitions
    "ADD_TASK_TOOL",
    "QUERY_TASKS_TOOL",
    "QUERY_CODE_CONTEXT_TOOL",
    "SUMMARIZE_DAY_TOOL",
    "QUERY_COURSEWORK_TASKS_TOOL",
    "GET_HACKATHON_DEADLINES_TOOL",
    "LOG_CODE_SNIPPET_TOOL",
    "LOG_CODE_CONTEXT_TOOL",
    "SEARCH_WEB_TOOL",
    "INGEST_URL_TOOL",
    "VERIFY_DEADLINE_TOOL",
    "UPDATE_TASK_STATUS_TOOL",
    "EDIT_TASK_TOOL",
    "DELETE_TASK_TOOL",
    "LIST_PROJECTS_TOOL",
    "QUERY_COURSEWORK_NOTES_TOOL",
    "SUMMARIZE_ACROSS_DOMAINS_TOOL",
    "CHAT_TOOL",
    "DETECT_DEADLINE_CONFLICTS_TOOL",
    "GET_CALENDAR_AVAILABILITY_TOOL",
    "PROPOSE_SCHEDULE_TOOL",
    "COMMIT_SCHEDULE_TOOL",
    "DETECT_SCHEDULE_CONFLICTS_TOOL",
    "DELEGATE_TO_SPECIALIST_TOOL",
    "ASSESS_FEASIBILITY_TOOL",
    "APPLY_TRIAGE_PLAN_TOOL",
    "BASE_TOOL_DEFINITIONS",
    "get_tool_definitions",
    "TOOL_DEFINITIONS",
    # Registry & Dispatch
    "SkillHandler",
    "SKILL_REGISTRY",
    "register_skill",
    "dispatch_skill",
    # Handlers
    "handle_search_web",
    "handle_ingest_url",
    "handle_verify_deadline",
    "handle_query_tasks",
    "handle_query_coursework_tasks",
    "handle_get_hackathon_deadlines",
    "handle_add_task",
    "handle_update_task_status",
    "handle_edit_task",
    "handle_delete_task",
    "handle_list_projects",
    "handle_detect_deadline_conflicts",
    "handle_query_code_context",
    "handle_log_code_context",
    "handle_log_code_snippet",
    "handle_summarize_day",
    "handle_query_coursework_notes",
    "handle_summarize_across_domains",
    "handle_chat_skill",
    "handle_get_calendar_availability",
    "handle_propose_schedule",
    "handle_commit_schedule",
    "handle_detect_schedule_conflicts",
    "handle_assess_feasibility",
    "handle_apply_triage_plan",
    "handle_delegate_to_specialist",
]
